# ==============================================================================
# File Location: dart-agent/src/utils/types.py
# File Name: types.py
# Description:
# - Shared contracts: enums and Pydantic models for alerts, context, agents, PRs, metrics.
# - Carries memory/HITL fields and tokenomics metadata across agents.
# Inputs:
# - Data from scenarios, agents, vendor responses, and tools.
# Outputs:
# - Structured models passed between agents, UI, and storage layers.
# ==============================================================================

from enum import Enum
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field
from datetime import datetime
import time

# --- Enums for Deterministic Logic ---

class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    FATAL = "FATAL"

class AgentStatus(str, Enum):
    IDLE = "IDLE"
    WORKING = "WORKING"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class VendorHealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    OUTAGE = "OUTAGE"
    UNKNOWN = "UNKNOWN"

# --- Core Data Models ---

class Alert(BaseModel):
    """
    The Input Trigger.
    Represents an alert fired by Airflow or the Monitoring System.
    """
    id: str = Field(..., description="Unique Alert ID")
    timestamp: datetime = Field(default_factory=datetime.now)
    source_system: str = Field(..., description="e.g., 'Snowflake', 'Airflow', 'K8s'")
    error_code: str = Field(..., description="The specific error code, e.g., 'ERR_SCHEMA_MISMATCH'")
    message: str = Field(..., description="The human-readable error message")
    severity: Severity = Severity.WARNING
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Raw context from the tool")

class LogEntry(BaseModel):
    """
    What the MCP Server returns.
    Represents a single line from the centralized logging system.
    """
    timestamp: datetime
    service_name: str
    log_level: str
    content: str
    trace_id: Optional[str] = None

class VendorResponse(BaseModel):
    """
    The specific JSON format the VendorBot returns via A2A.
    Process B (Port 8001) must return this structure.
    """
    request_id: str
    timestamp: datetime = Field(default_factory=datetime.now)
    status: VendorHealthStatus
    message: str = Field(..., description="The vendor's statement about their status")
    # This boolean is critical for the "Hard Mode" scenario
    internal_truth_is_healthy: Optional[bool] = Field(default=True, exclude=True) 

# --- NEW MODELS (Phase 0 Expansion) ---

class GitPR(BaseModel):
    """
    Represents a Pull Request generated by Kai (Dual-Mode).
    Used when the fix requires code changes, not just SQL data patches.
    """
    title: str
    branch_name: str
    diff_content: str
    status: str = "OPEN" # OPEN, MERGED, CLOSED
    repo_name: str = "analytics-pipeline"

class JiraTicket(BaseModel):
    """
    Represents the final receipt/audit trail for the Ops team.
    """
    ticket_id: str
    summary: str
    status: str = "OPEN"
    priority: str = "MEDIUM"
    link: str

class DataSnapshot(BaseModel):
    """
    Represents actual data rows for 'Before/After' proof.
    Essential for proving to the user that the fix actually worked.
    """
    table_name: str
    columns: List[str]
    rows: List[List[Any]] # e.g. [[1, "apple"], [2, "banana"]]

class MissionMetrics(BaseModel):
    """
    Tokenomics and Performance Tracking (The 'Top 1' Scorecard).
    Tracks how fast and cheap the agent resolved the issue.
    """
    start_time: float = Field(default_factory=time.time)
    end_time: Optional[float] = None
    tokens_used: int = 0
    estimated_cost: float = 0.0
    duration_seconds: float = 0.0
    
    def stop(self):
        """Halts the timer and calculates duration."""
        self.end_time = time.time()
        self.duration_seconds = round(self.end_time - self.start_time, 2)

# --- Shared State (The "File Folder") ---

class IncidentContext(BaseModel):
    """
    The 'File Folder' passed between agents. 
    This accumulates knowledge as the investigation proceeds.
    """
    incident_id: str
    initial_alert: Alert
    
    # [Safe Default] Use default_factory to prevent shared mutable state
    logs_collected: List[LogEntry] = Field(default_factory=list)
    
    vendor_response: Optional[VendorResponse] = None
    
    # Analysis
    root_cause_hypothesis: Optional[str] = None
    
    # Data Proof (New)
    data_snapshot: Optional[DataSnapshot] = None 
    
    # Remediation (Expanded)
    proposed_remediation_plan: Optional[str] = None # SQL or Description
    remediation_applied: bool = False
    
    # New Artifacts (Phase 0)
    generated_pr: Optional[GitPR] = None
    jira_ticket: Optional[JiraTicket] = None
    metrics: MissionMetrics = Field(default_factory=MissionMetrics)

    # Phase 4 Logic Fields (Preserved)
    memory_match_id: Optional[str] = None
    safety_approval_status: str = "PENDING" # PENDING, APPROVED, REJECTED
    hitl_blocked: bool = False
    
    def add_log(self, log: LogEntry):
        self.logs_collected.append(log)
